<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Sales_Items_Column_Qty
 * @var Mage_Adminhtml_Block_Sales_Items_Column_Qty $this
 */
?>
<?php if ($_item = $this->getItem()): ?>
<table cellspacing="0" class="qty-table">
    <tr>
        <td><?php echo Mage::helper('sales')->__('Ordered') ?></td>
        <td><strong><?php echo $_item->getQtyOrdered() * 1 ?></strong></td>
    </tr>
    <?php if ((float) $_item->getQtyInvoiced() !== 0.0): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Invoiced') ?></td>
        <td><strong><?php echo $_item->getQtyInvoiced() * 1 ?></strong></td>
    </tr>
    <?php endif ?>
    <?php if ((float) $_item->getQtyShipped() !== 0.0): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Shipped') ?></td>
        <td><strong><?php echo $_item->getQtyShipped() * 1 ?></strong></td>
    </tr>
    <?php endif ?>
    <?php if ((float) $_item->getQtyRefunded() !== 0.0): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Refunded') ?></td>
        <td><strong><?php echo $_item->getQtyRefunded() * 1 ?></strong></td>
    </tr>
    <?php endif ?>
    <?php if ((float) $_item->getQtyCanceled() !== 0.0): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Canceled') ?></td>
        <td><strong><?php echo $_item->getQtyCanceled() * 1 ?></strong></td>
    </tr>
    <?php endif ?>
</table>
<?php endif ?>
