name: Spellcheck

on:
  workflow_call:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Spelling
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          config_path: .github/spellcheck.yml
          task_name: Markdown
          output_file: spellcheck-output.txt
      - uses: actions/upload-artifact@v4
        if: '!cancelled()'
        with:
          name: Spellcheck Output
          path: spellcheck-output.txt
