name: Spellcheck

on:
  workflow_call:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Spelling
        uses: rojopolis/spellcheck-github-actions@latest
        with:
          config_path: .github/spellcheck.yml
          task_name: Markdown
